### ISSUE TITLE
Sequentially Bootstrapping Question

### ISSUE THREAD

**Issue by jmrichardson** [hudson-and-thames/mlfinlab#133]
First thank you for your work!

I am have a dumb question regarding the SequentiallyBootstrappedBaggingClassifier:

The price_bars parameter is defined in the docs as a DataFrame of price bars used in samples_info_sets (Triple Barrier Events) generation.  Following along in the research, the triple_barrier_events generation looks like:

```
triple_barrier_events = ml.labeling.get_events(close=data['close'],
                                               t_events=cusum_events,
                                               pt_sl=pt_sl,
                                               target=daily_vol,
                                               min_ret=min_ret,
                                               num_threads=3,
                                               vertical_barrier_times=vertical_barriers,
                                               side_prediction=data['side'])
```

So would the price_bars parameter be the data frame "data" from above?  

The example given in the docs reads price_bars parameter from the saved csv dataframe which expects to have dates in the index and 2nd column:

```
...
triple_barrier_events = pd.read_csv('BARRIER_FILE_PATH', index_col=0, parse_dates = [0, 2])
price_bars = pd.read_csv('PRICE_BARS_FILE_PATH', index_col=0, parse_dates = [0, 2])
...
```

The dataframe for the above "data" dataframe does not have dates in the 2nd column (it's the high column from OHLC).

Thanks for any help!

**Comment by proskurin** [comment]
Hey @jmrichardson 
Thank you for your interest to mlfinlab package! Sorry, it is our fault, docs should be:
`price_bars = pd.read_csv('PRICE_BARS_FILE_PATH', index_col=0, parse_dates = [0])`, you pass to price_bars.close as algorithm param in SequentiallyBootstrappedBaggingClassifier. However, the algorithm only needs date_time index of price bars so it actually doesn't matter if you path price_bars.close or price_bars.high because price info is not used in indicator matrix generation, only datetime index.

**Comment by jmrichardson** [comment]
Thank you and really do appreciate this package!
