### ISSUE TITLE
get_daily_vol function bug

### ISSUE THREAD

**Issue by sukioral** [hudson-and-thames/mlfinlab#188]
I am not 100% sure whether this is a bug or not.

I am using HSI futures (2014-01-01 to 2014-06-30) data to form dollars bars using threshold of 100000000. When I am trying to use get_daily_vol function to get the volatility threshold and type in a value for the lookback period, I discovered from the result that no matter the lookback period equals to 10 / 50 / 100, the daily_vol series always starts on the 63rd dollar bar with a NAN and followed by different numeric values till the end.

Is there any bug for the function? Because I assume the lookback period should somehow affect the starting point of the daily_vol series. Thank you.

**Comment by Harkishan-99** [comment]
Hi @sukioral Actually that is not a bug. The lookback period is only for estimating the weights of exponential moving function. Ref : https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.ewm.html 
The first Nan value is due to the calculation of daily returns and the pandas.series.ewm function does return any Nan based on span (loockback) parameter.
