### ISSUE TITLE
Add Backtest Satistics to import from mlfinlab by default.

### ISSUE THREAD

**Issue by PanPip** [hudson-and-thames/mlfinlab#226]
Currently, Backtest Statistics part import is only available via 
`import mlfinlab.backtest_statistics.statistics`
and not available from 
`import mlfinlab`

**Comment by Jackal08** [comment]
Thats because you have not exposed the module via the root `__init__.py` file.

You will have to make that change locally and then run then uninstall the currentl version of the package, cd into your local mlfinlab dir and then in the terminal `pip install -e .` That will install and run the package from your local copy. You will be able to make changes there until you are ready to push back to branch.
