### ISSUE TITLE
Update Pandas Dependency

### ISSUE THREAD

**Issue by kivo360** [hudson-and-thames/mlfinlab#228]
This isn't necessarily a problem, just something that causes issues inside of my dependency tree usually.

I noticed pandas `0.25.3` is the main dependency for `mlfinlab`. Pandas 1.0.1 is compatible with many of the systems available and is faster. It also doesn't break dependency trees like mine.

**Describe the solution you'd like**
I'd like pandas `0.25.3` to be upgraded to pandas `1.0.1` at the very least.

**Comment by MislavSag** [comment]
I am using mlfinlab with Pandas 1.0.3. but have some difficulties. For example, I tried yesterday to use `get_av_uniqueness_from_triple_barrier` function but it didn't work and it turned out it was a bug in new Pandas: https://github.com/pandas-dev/pandas/issues/32762

I have also send one pull request for Tripple barrier labeling to work https://github.com/hudson-and-thames/mlfinlab/pull/223

Function get_evetns works only for one thread. For more threads, it just runs forever.

There are probably more problems I didn't encounter yet.

**Comment by Jackal08** [comment]
Hi @kivo360,

We are updating all the packages in this weekend version release. 

Best regards
Jacques Joubert
