### ISSUE TITLE
MemoryError: Unable to allocate array in SequentiallyBootstrappedBaggingClassifier

### ISSUE THREAD

**Issue by MislavSag** [hudson-and-thames/mlfinlab#241]
I am trying to implement SequentiallyBootstrappedBaggingClassifier in the following way:

```
clf = SequentiallyBootstrappedBaggingClassifier(
    samples_info_sets=triple_barrier_events.reindex(X_train.index).t1,
    price_bars = spy.loc[X_train.index.min():X_train.index.max(), 'close_orig'],
    n_estimators=10, base_estimator=clf_base, random_state=1,
    n_jobs=8, oob_score=False, max_features=10)
```
but I got an error:

> MemoryError: Unable to allocate array with shape (1262264, 27618) and data type float64

As you can see my price_bars argument has 1.262.264 elements (vector of prices) and, at the same time, I have 27.618 triple-barrier events. Is the only solution to downsample my sample (or buy more RAM-s :)), or is there a possibility to change the bagging classifier to make it more robust to big samples?

**Comment by Gunther-Schulz** [comment]
Hi, did you ever solve this? What OS are you using?

**Comment by MislavSag** [comment]
I didn't solve it. I am on windows 10. You can try to give the function lots of data (large number of rows and columns) and should return error in the commented issue.

**Comment by PanPip** [comment]
@MislavSag thank you for proposing this enhancement.

This issue is very specific and related to feeding large datasets to functions. This can be tackled by pre-processing and splitting such datasets into smaller ones. Adjusting MlFInLab functions to take large datasets as input would require much work and for current applications of the MlFinLab package is unnecessary.

If you would like to add a function that allows such data pre-processing, please make PR. 🙂
