### ISSUE TITLE
Sample weights / review

### ISSUE THREAD

**Issue by decastro-alex** [hudson-and-thames/mlfinlab#329]
**see my comments after the <-- arrow

In this case we see that A used information about returns on :math:`[t_1,t_8]` to generate label-endtime which overlaps
with :math:`[t_3, t_6]` which was used by B, however C didn't use any returns information which was used by to label
other samples. Here we would like to introduce the concept of concurrency.
other samples. Here we would like to introduce the concept of concurrency. <-- small comment: doesn't C overlap with A on [t_7, t_8], and therefore depends on r_8? Or do we want to say C doesn't overlap with BOTH A, and B

**Comment by boyboi86** [comment]
@decastro-alex 

Using your analogy:

A used information about returns on : [t_1,t_8] to generate label-endtime which overlaps
with B:[t_3, t_6] 

If total samples are  [t_1,t_8]. Then C will guarantee to overlap, since A already occupied all the possible t0 to t1.

Concurrency concept itself has nothing to do with returns, but rather uniqueness of each events i.e. A, B or C. (r_8? I'm assuming "r" stands for return)

However, if all possible start time (t0) to end time (t1) was [t_1, t_11] instead. The only way for C to be highly unique would be [t_9, t_11]. In that case, if A, B was chosen C will be reflected with a very high probability to be next pick.

However, do take note as np.random.choice may not choose samples that were assigned higher probabilities, based on my experience (Not sure why, probably because its "random?").

Did I answer your question? If not please further elaborate.

**Comment by Jackal08** [comment]
Hi @decastro-alex, 

I hope @boyboi86 was able to answer your question? If not, our Slack channel is a really great place to bounce ideas and get further clarity. It is open to sponsors of the group. I think you would enjoy it: https://www.patreon.com/HudsonThames

Best regards
Jacques
