### ISSUE TITLE
part of the trades are not captured in the bars

### ISSUE THREAD

**Issue by Andrey776** [hudson-and-thames/mlfinlab#367]
**Describe the bug**
Observe the consistent difference in sums of bars and initial dataset

**To Reproduce**
see printscreen

**Expected behavior**
sums should be equal

**Screenshots**
pls find below

**Desktop (please complete the following information):**
OS: [e.g. iOS] 10.15.5 (19F101)
Browser - chrome Version 83.0.4103.97 (Official Build) (64-bit)

<img width="712" alt="Screen Shot 2020-06-06 at 22 55 05" src="https://user-images.githubusercontent.com/61335235/83960719-43b16680-a849-11ea-8a32-3e58bc3e6926.png">

**Additional context**

**Comment by PanPip** [comment]
@Andrey776 thank you for reporting this issue.

How can it be reproduced?

**Comment by PanPip** [comment]
Closing stale issue.

**Comment by Jackal08** [comment]
I should add that when a very large trade comes in, say 2 times bigger than the threshold, we only sample once and discard the remainder volume, then count from the next trade.

This was deliberate as the threshold is used to signal when to sample as a proxy for information. Thus sampling multiple times oer trade doesnt make sense.

The cum volume, price, and ticks in the output dataframe is to be used for sanity checks. For example the cum ticks should always be the same if using tick bars but vol bars wont always be exact because we discard the remainders.
