### ISSUE TITLE
Use parquet file format instead of csv for get_dollar_bars() etc

### ISSUE THREAD

**Issue by stnatter** [hudson-and-thames/mlfinlab#454]
**Is your feature request related to a problem? Please describe.**
Can I suggest to change the file format requirement for get_dollar_bars() and similar functions to use [parquet](https://wesmckinney.com/blog/python-parquet-update/)  file format instead. Parquet also works with [Dask](https://dask.org) which can speed up the precessing even more.

**Describe the solution you'd like**
read and write files as parquet file format instead of CSV.
In addition it would be more convenient to pass in the relevant columns separately to remove the necessity to be constrained to 3 columns only in the file. This can be easily done in parquet.

**Describe alternatives you've considered**
Alternatively HDF5 could be considered too.

**Additional context**
The processing can be sped up in any case by using Dask. Works with CSV and parquet.

**Comment by stnatter** [comment]
Closing since there is no reply and your licence is not really opensource I have no interest to contribute.

**Comment by Jackal08** [comment]
Hi @stnatter, 

Thank you for the suggestion.

* Maybe in the future, we can add something like this.
* We don't want to add further dependencies since it makes maintenance more difficult. 
* There isn't any incentive for us to improve the data structures part of the code since it will only work in a research environment and its current speed is not a blocker.
