### ISSUE TITLE
Arbitragelab request - auto kalman filter

### ISSUE THREAD

**Issue by andrewcztrack** [hudson-and-thames/mlfinlab#461]
Hi All!
Love the library!

I think the below would be a good addition.

https://github.com/cvxgrp/auto_ks
http://web.stanford.edu/~boyd/papers/auto_ks.html

**Comment by PanPip** [comment]
Thank you for the suggestion @andrewcztrack.

I'm tagging @proskurin who is currently busy adding Kalman filter to MlFinLab to check this package.

**Comment by PanPip** [comment]
Just asked @proskurin.

We'll be adding functionality to apply the Kalman filter to pairs trading in the new [ArbitrageLab](https://hudsonthames.org/statistical-arbitrage/) package 👍

**Comment by andrewcztrack** [comment]
Thank you @PanPip !! I will be joining the slack channel next month.
Looking forward to it :).
Best,
Andrew

**Comment by proskurin** [comment]
@andrewcztrack  thank you very much for your suggestion. We've made an extensive research regarding Kalman filter tuning and found out that tuning Kalman filter is more of an art rather than science. There are so many ways to do that starting from ALS to cross-validation. That is why we decided not to implement auto-Kalmantuning, because:
1) PyKalman already has EM-algorithm to tune Kalman filter params
2) At the end, a researcher will choose domain-specific method to tune the parameters
