### ISSUE TITLE
Trouble adding vertical barriers to CUSUM output

### ISSUE THREAD

**Issue by vjtrost88** [hudson-and-thames/mlfinlab#471]
**Python version:** 3.7.6
**mlfinlab version:** 0.15.0

I'm working through the Chapter 3 exercises in AFML on p 55, specifically problem 3.1. 

Instead of the E-mini S&P 500 futures, I'm using a XBT futures dataset. I had no problem forming dollar bars with this tick data so I'm confident that's not the issue here.

Part (a) says to apply a CUSUM filter where the threshold is the std dev of daily returns. Things started to get weird here...

I didn't specify the `time_stamps` param which defaults to true, and it seems to be appending the index of my events to the beginning of unix time. **(possible bug number 1 at chunk 8)**

-----------

<img width="869" alt="image" src="https://user-images.githubusercontent.com/19673777/100189122-a5c65c80-2eb9-11eb-881c-2449641effa0.png">

-----------

I thought "no big deal, I can set `time_stamps=False` and use the indices to subset the correct `date_time`s. It made sense to me that the goal here was to get the timestamps where the events are, correct me if I'm missing something. This worked:

-----------
<img width="852" alt="image" src="https://user-images.githubusercontent.com/19673777/100188901-38b2c700-2eb9-11eb-9d68-9c04e5f2fc66.png">

-----------

Part (b) of the question says to use Snippet 3.4 on a pandas series `t1`, where `numDays=1`. I knew `mlfinlab` had that snippet implemented as the `add_vertical_barrier` function, so I read the dosctring and tried to use it. I noticed my events were closer together than 1 day, so I adjusted accordingly. Here was my output **(possible bug number 2)**:

-----------

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/19673777/100188237-cc839380-2eb7-11eb-9954-03446ef70e21.png">

-----------

I need timestamps of vertical barriers to go on and use them in the `get_events` function if I'm understanding things correctly. However, I'm stumped by this "invalid type promotion" error. Please let me know if I've gone wrong somewhere in the usage. Apologies for the verbosity as well, but I've been thoroughly enjoying learning/implementing thus far. 

Thanks for all the hard work and thanks for the help in advance.

**Comment by PanPip** [comment]
Hi @vjtrost88. Thank you for reporting this!

May I ask you to also provide a small test dataset that you were using to reproduce this issue?

**Comment by vjtrost88** [comment]
Sure! See attached...
[XBT_dollar_bar_sample.csv.zip](https://github.com/hudson-and-thames/mlfinlab/files/5643067/XBT_dollar_bar_sample.csv.zip)

**Comment by PanPip** [comment]
Hi @vjtrost88, thanks for the dataset.

I was able to reproduce your issue.

### Regarding the possible bug number 1:
The `cusum_filter` function outputs index from the beginning of the Unix time since the `pd.Series` that are given to the method has numbers as index.
![image](https://user-images.githubusercontent.com/16906989/102207852-f0dafa80-3ece-11eb-845e-45cea947fb14.png)

This issue can be easily fixed if you set your `date_time` column as index in a `DateTime` format:
![image](https://user-images.githubusercontent.com/16906989/102207999-27b11080-3ecf-11eb-9db2-4c515564a051.png)

### Regarding the possible bug number 2:
Again this issue is related to the index not being in a `DateTime` format. Here is the output of `add_vertical_barrier` function using the variable from the previous image:
![image](https://user-images.githubusercontent.com/16906989/102208382-a443ef00-3ecf-11eb-8f2e-21c37f64be07.png)

Note: using the flag `time_stamps=False` will only result in the output of the same values but in a form of a list instead of the standard `DatetimeIndex`. The `add_vertical_barrier` function won't work with this type as an input.
![image](https://user-images.githubusercontent.com/16906989/102208564-dead8c00-3ecf-11eb-901d-d931dfcde669.png)

Thanks for using the MlFinLab package. Hope this answer helps 🙂

**Comment by vjtrost88** [comment]
Thank you @PanPip , i will pay closer attention to my types!
