### ISSUE TITLE
Some dependency issues happened during the installation of mlfinlab and vectorbt

### ISSUE THREAD

**Issue by gary9716** [hudson-and-thames/mlfinlab#477]
**Is your feature request related to a problem? Please describe.**
Hi, recently I consider becoming one of the sponsor and using your library in my trading bot, so I first tested the compatibility on docker with python 3.7.9 installed.
After I installed the vectorbt, which is a backtesting framework for my bot, I realized that vectorbt depend on an library called numba with the version >= 0.50.1. But mlfinlab needs the version exactly equal to 0.49.1. I didn't find a good solution to resolve this. So I wonder if it's possible for you to loose the dependency of numba to make the installation smoother. 

**Describe alternatives you've considered**
Currently I'm using miniconda to manage these dependencies but it also gave the warning of this issue I mentioned above.

Best regards, KT

**Comment by gary9716** [comment]
If there isn't any backward compatible issue on numba, loosing the condition to "numba >= 0.49.1" will help a lot !
Thanks.

**Comment by mrajancsr** [comment]
Can you guys remove me from this garbage notification?  I keep clicking unsubscribe but keep getting these garbage notifications from ur library.

**Comment by Jackal08** [comment]
@mrajancsr Sorry but you have subscribed to the repo, my guess is that its because you are watching the repo. It has nothing to do with us. I have checked, in no way are you linked to our organisation. 

You may need to unwatch, or stop following the repo.

**Comment by Jackal08** [comment]
Hi @gary9716, 

Unfortunately, we can't change the version numbers, if we do, something will break. 

We noticed that many users expect to have relaxed versioning but everytime we change the versions, our unit tests pick up breaking changes. Thank God for 100% coverage. 

We do update our libraries once a year, the next one is scheduled around April 2021. 

You can also add a flag to your pip install to not install the dependencies. This would work but it's risky since I am quite confident something will break and you won't be able to tell which parts.
