### ISSUE TITLE
'pip install mlfinlab' doesn't work

### ISSUE THREAD

**Issue by kinivi** [hudson-and-thames/mlfinlab#487]
Simple `pip install mlfinlab` stoped working for me yesterday. Both in Google Colab and local env. 
Just the error 

<img width="632" alt="Screenshot 2021-02-18 at 10 57 51" src="https://user-images.githubusercontent.com/13486777/108332499-8ac56900-71d8-11eb-96e8-d48f393e0d1f.png">

I also tried `pip install mlfinlab==1.0.0` but the same error. Previously it works well without any issues. 

Environment: Google Colab

**Comment by sanderson4030** [comment]
I got this same error, but resolved it by using python 3.8. now on a fresh 3.8 environment there's a new error:
`ERROR: Cannot install mlfinlab and mlfinlab==1.0.0 because these package versions have conflicting dependencies.`
Caused by:
`    mlfinlab 1.0.0 depends on numpy==1.20.1`
`    tensorflow 2.2.1 depends on numpy<1.19.0 and >=1.16.0`

**Comment by Jackal08** [comment]
Hi All, 

Unfortunately due to a NumPy version release, which has breaking changes for cvxpy and TF, we have had no choice but to update the libraries to specific versions of cvxpy, NumPy, and TF. It also means you have to use Python 3.8 and  pip==20.1.1.

It is very very important that you use the versions we specify. By using other versions we can't guarantee that the code will work as expected. In fact, we know that it won't.

We are going to drop the TF dependency which will make the library much lighter but you will need to install it if you want to use synthetic data generation.

We will release 1.0.1 today. 

Best regards
Jacques Joubert

**Comment by PanPip** [comment]
@kinivi, @sanderson4030 Thank you for addressing these issues.

We've just released MlFinLab patch v1.0.1 and removed TF from the list of dependencies. However, Python 3.8 is still required.

Please update your MlFinlab versions and tell us if the issue is resolved.
