### ISSUE TITLE
Python 3.9

### ISSUE THREAD

**Issue by peoples-hedge-fund** [hudson-and-thames/mlfinlab#503]
Package install doesn't work because of numba 0.52.0 dependency. 

Python versions: 3.6-3.8
llvmlite 0.35.*
NumPy >=1.15 (can build with 1.11 for ABI compatibility)

any of the following versions would satisfy the requirements

ERROR: Could not find a version that satisfies the requirement numba==0.52.0 (from versions: 0.1, 0.2, 0.3, 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.2, 0.13.3, 0.13.4, 0.14.0, 0.15.1, 0.16.0, 0.17.0, 0.18.1, 0.18.2, 0.19.1, 0.19.2, 0.20.0, 0.21.0, 0.22.0, 0.22.1, 0.23.0, 0.23.1, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.28.1, 0.29.0, 0.30.0, 0.30.1, 0.31.0, 0.32.0, 0.33.0, 0.34.0, 0.35.0, 0.36.1, 0.36.2, 0.37.0, 0.38.0, 
0.38.1, 0.39.0, 0.40.0, 0.40.1, 0.41.0, 0.42.0, 0.42.1, 0.43.0, 0.43.1, 0.44.0, 0.44.1, 0.45.0, 0.45.1, 0.46.0, 0.47.0, 0.48.0, 0.49.0, 0.49.1rc1, 0.49.1, 0.50.0rc1, 0.50.0, 0.50.1, 0.51.0rc1, 0.51.0, 0.51.1, 0.51.2, 0.52.0rc2, 0.53.0rc1.post1, 0.53.0rc2, 0.53.0rc3, 0.53.0, 0.53.1)

**Comment by peoples-hedge-fund** [comment]
Beyond that, it's a bit sad that this can't be run on Colab either - as this is the primary way in which data scientist do quick exploration.

**Comment by PanPip** [comment]
Hi @peoples-hedge-fund,

Thank you for adding this ticket and reaching out. 

Unfortunately, right now we only support Python 3.8, as we've had issues a few months ago with finding the matching dependency versions configuration due to cvxpy and numpy packages conflicts. 

We'll add support for the other versions of python (hopefully 3.7 and 3.9) in the future, once we can find a stable configuration that would work for our packages (MlFinLab, PortfolioLab and ArbitrageLab).

Does installing MlFinlab on Python 3.8 work for you at the moment?

**Comment by peoples-hedge-fund** [comment]
@PanPip I am sure installing it on 3.8 works, its just a bit problematic on Colab (even when i configure it to 3.8) which is how I share research with executives.

**Comment by PanPip** [comment]
Hi @peoples-hedge-fund,

We've recently released MlFinLab 1.3.0, which supports Python 3.8, 3.7, and 3.6. Now it can be used on Google Colab 🙌 

We've also relaxed the hard dependencies, which means integration in existing environments will be much easier.
