### ISSUE TITLE
Installing mlfinlab on Python 3.7.9

### ISSUE THREAD

**Issue by legendagain** [hudson-and-thames/mlfinlab#509]
Hello! Thank you very much for this great project.

I am trying to run `pip install mlfinlab` but unfortunately I get the following error messages:

`ERROR: Could not find a version that satisfies the requirement mlfinlab (from versions: none)`
`ERROR: No matching distribution found for mlfinlab`

I am currently running Python 3.7.9, and my understanding (from [here](https://github.com/hudson-and-thames/mlfinlab/issues/503)) is that Python 3.7 is supported. What am I missing?

**Comment by Jackal08** [comment]
Hi @legendagain, 

Thanks for the kind feedback, glad that you are enjoying the product. 

mlfinlab does work on python 3.7 however the error you are getting is because we no longer provide free access to the libraries. All of them can be purchased on a subscription plan via the website: https://hudsonthames.org/mlfinlab/

**Comment by legendagain** [comment]
Thanks for the message @Jackal08! :)
