### ISSUE TITLE
Run bars threshold condition should be changed

### ISSUE THREAD

**Issue by proskurin** [hudson-and-thames/mlfinlab#52]
expected proportion of buy/sell ticks * expected_buy/sell_volume instead of expected proportion

**Comment by atokuz** [comment]
Hi,
I believe the problem is in exp_buy/sell_proportion calculation in _get_expected_imbalance function. Since buy array has 0 for sell ticks and sell array has 0 for buy ticks, calculated ewma result would naturally give the expected value for the next tick. I think there is no need to divide it to total number of ticks. 
[https://github.com/hudson-and-thames/mlfinlab/pull/64](url)

**Comment by proskurin** [comment]
Hi!
Did you look at master or dev branch ? In dev branch implementation we don’t put 0 for buy/sell ticks. Current implementation is in dev branch

**Comment by Jackal08** [comment]
@proskurin, can we close this ticket?

**Comment by proskurin** [comment]
No, we need to complete PR by Atokuz
