### ISSUE TITLE
Create seq bootstrap RF

### ISSUE THREAD

**Issue by Jackal08** [hudson-and-thames/mlfinlab#91]

**Comment by imcu** [comment]
I have a proposal on how to proceed with this implementation.

Implement a custom MlBaggingClassifier similar to this one below, which is a class derived from `sklearn.ensemble.BaggingClassifier`

https://imbalanced-learn.readthedocs.io/en/stable/generated/imblearn.ensemble.BalancedBaggingClassifier.html#imblearn.ensemble.BalancedBaggingClassifier

https://github.com/scikit-learn-contrib/imbalanced-learn/blob/12b2e0d/imblearn/ensemble/_bagging.py#L25

Where, instead of the RandomSampler that is here
https://github.com/scikit-learn-contrib/imbalanced-learn/blob/12b2e0d/imblearn/ensemble/_bagging.py#L221

we implement our own MlSequentialSampler that would follow the steps in the book

Here’s an example implementation of a sampler
https://github.com/scikit-learn-contrib/imbalanced-learn/blob/12b2e0d2858a30d4687fbf910372b8f416b33998/imblearn/under_sampling/_prototype_selection/_random_under_sampler.py#L24

Following the guideline below, we can use the sampler with other algorithms as well
https://imbalanced-learn.readthedocs.io/en/stable/auto_examples/pipeline/plot_pipeline_classification.html

Thoughts ?
